extern const unsigned short arrowTiles[32];
extern const unsigned short arrowPal[256];
int arpos, i, g_newframe, frames;
extern const unsigned short l1Tiles[32768];
extern const unsigned short l1Map[1024];
extern const unsigned short l1Pal[256];
extern const unsigned char such[23719];
extern const unsigned short blockTiles[512];
extern const unsigned short blockPal[256];