CFLAGS = -Wall -O3 -ffast-math -mlong-calls -mcpu=arm7tdmi -mtune=arm7tdmi -marm -faggressive-loop-optimizations -fverbose-asm 
ARCH = -mthumb -mthumb-interwork
CPPFLAGS = 
SOURCES = main.c
HEADERS = inc/soundbank.h
ASMFLAGS = -mcpu=arm7tdmi
ASMINC = 
SPECS = -specs=gba.specs
PATH = C:\devkitPro\devkitARM\bin
PREFIX = \arm-none-eabi-
LIBS = -lheart -lm
PROGNAME = sample
CDATA = smp.c such.s soundbank.s
GBFSFILE = build/data.hrt
COMPFILES = build/soundbank.bin
OBJECTS = build/main.o build/smp.o build/soundbank.out build/such.out
INTERNALNAME = SAMPLE
GAME_CODE = SMPL
VERSION = 1
LIBDIRS = -LC:\devkitPro\devkitARM\lib
MAXMODDATA = data/franky.s3m data/complete2.wav
MAXMODFILE = soundbank


include C:\devkitPro\devkitARM\hrt_system\hrt_standard_targets.mak