CFLAGS = -Wall -O3 -ffast-math -mlong-calls -mcpu=arm7tdmi -mtune=arm7tdmi -marm -faggressive-loop-optimizations -fverbose-asm 
ARCH = -mthumb -mthumb-interwork
CPPFLAGS = 
SOURCES = main.c
HEADERS = inc/soundbank.h
ASMFLAGS = -mcpu=arm7tdmi
ASMINC = 
PATH = C:\devkitPro\devkitARM\bin
PREFIX = \arm-none-eabi-
LIBS = -lheart -lm
PROGNAME = sample
CDATA = smp.c such.s soundbank.s
GBFSFILE = 
COMPFILES = build/soundbank.bin data/such.bin
OBJECTS = build/main.o build/smp.o build/soundbank.out build/such.out
INTERNALNAME = SAMPLE
GAME_CODE = SMPL
VERSION = 1
LIBDIRS = 
MAXMODDATA = data/franky.s3m data/complete2.wav
MAXMODFILE = soundbank
HRT_CFLAGS = -DHRT_USE_MBV2LIB -DHRT_BITFIELD_TYPES -DHRT_ADMIN
USE_MULTIBOOT = yes

include C:\devkitPro\devkitARM\hrt_standard_targets.mak

# CUSTOM MAKEFILE TARGETS START HERE

