extern const unsigned short blockTiles[512];
extern const unsigned short blockPal[256];
extern const unsigned short arrowTiles[32];
extern const unsigned short arrowPal[256];
int x, y, rot, x_scale, y_scale, fxlevel, fxmode, arpos;
int frames;
extern const unsigned short bg_hillTiles[32800];
extern const unsigned short bg_hillMap[2048];
extern const unsigned short bg_hillPal[256];
extern const unsigned short suchBitmap[38400];
extern const unsigned short plasmaBitmap[38400];
extern const unsigned short plasmaPalette[256];
extern const unsigned short hrt_snd[5252832];
extern const unsigned short conceptBitmap[38400];
extern const unsigned short conceptPal[256];
extern const unsigned short ballsTiles[32768];
extern const unsigned short ballsMap[1024];
extern const unsigned short ballsPal[256];
extern const unsigned short busterTiles[512];
extern const unsigned short busterPal[16];